#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Check for Homebrew,
# Install if we don't have it
if test ! "$(which brew)"; then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae.
brew upgrade --all

# ===============================================
# Utilities
# ===============================================

# Install GNU core utilities (those that come with OS X are outdated).
brew install coreutils
if [ ! -L /usr/local/bin/gsha256sum ]; then
  sudo ln -sf /usr/local/bin/gsha256sum /usr/local/bin/sha256sum
fi
# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names
# GRC colorizes unix tools
brew install grc

# Install more recent versions of some OS X tools.
brew install zsh
brew install zsh-completions
brew install vim --override-system-vi

# Manage services with `brew services`
# Small wrapper around launchctl
brew tap homebrew/services

# Common useful binaries
brew install shellcheck
brew install the_silver_searcher
brew install ack
brew install rename
brew install htop
brew install tree
brew install fasd
brew install entr
brew install fzf
brew install jq

# Version control (Git)
brew install git
brew install git-extras
brew install diff-so-fancy
# brew install bfg

# Network tools
brew install ngrep
brew install httpie
brew install httrack

# Imaging tools
# brew install imagemagick --with-webp --with-fontconfig
# brew install ffmpeg --with-libass --with-fontconfig
# brew install giflossy

# ===============================================
# Languages
# ===============================================

# Development environment
# brew install nginx
# brew install dnsmasq
# brew install awscli
# brew install heroku

# JavaScript
# https://github.com/creationix/nvm
# brew install yarn --without-node
# npm install -g np david
# npm install -g svgo uglify-js
# npm install -g typescript source-map-explorer


# Scala
# brew install sbt
# brew install scala
# brew install typesafe-activator

# Python
# brew install python
# brew install bpython
# pip install --upgrade pip setuptools wheel virtualenv

# Ruby
# brew install ruby
# If doing more than casual ruby:
# brew install rbenv
# brew install rbenv-gem-rehash
# brew install ruby-build

# Go
# brew install go

# Haskell
# brew cask install haskell-platform

# Clojure
# brew install leiningen

# Elixir
# brew install elixir

# Elm
# brew cask install caskroom/cask/elm-platform

# Remove outdated versions from the cellar
brew cleanup
