" .vimrc
" This config is designed to be a minimal but useful vim config
" primarily for use where a more feature rich setup is either
" not needed or unavailable

" Install vim-plug if not already present
if empty(glob('$HOME/.vim/autoload/plug.vim'))
  silent execute '!curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Configure plugins
call plug#begin()

  Plug 'tpope/vim-sensible'
  Plug 'preservim/nerdtree'

call plug#end()

" Map <leader> key to space
let mapleader = " "
let g:mapleader = " "

" Fast saving and quitting
nmap <leader>w :w!<cr>
nmap <leader>q :q<cr>

" Display incomplete commands.
set showcmd

" Display the mode you're in.
set showmode

" Handle multiple buffers better.
set hidden

" Enable case-insensitive searching by default,
" but case-sensitive if expression contains a capital letter.
set ignorecase
set smartcase

" Put all swap files together in one place
set directory^=$HOME/.vim/tmp/

" Set tabwidth for gitcommit
autocmd Filetype gitcommit setlocal spell textwidth=72

" Set the terminal's title
set title

" Turn on line wrapping.
set wrap

" Show additional lines of context around the cursor.
set scrolloff=3

" Show line numbers.
set number

" Display extra whitespace
set list listchars=tab:»·,trail:·

" Settings that depend on plugins
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Go to tab by number
noremap <leader>1 1gt
noremap <leader>2 2gt
noremap <leader>3 3gt
noremap <leader>4 4gt
noremap <leader>5 5gt
noremap <leader>6 6gt
noremap <leader>7 7gt
noremap <leader>8 8gt
noremap <leader>9 9gt
noremap <leader>0 :tablast<cr>
