#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Homebrew if we don't have it
if test ! "$(which brew)"; then
  echo "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Manage services with `brew services`
# Small wrapper around launchctl
brew tap homebrew/services

# ===============================================
# Brews
# ===============================================

# Install more recent versions of some OS X tools.
brew install zsh
brew install zsh-completions
brew install vim

# Pure prompt
brew install pure

# Common utilities
brew install autojump
brew install htop
brew install tree
brew install ack
brew install the_silver_searcher
brew install fzf
brew install entr
brew install httpie
brew install jq
brew install yq

# Version control (Git)
brew install git
brew install git-delta
brew install git-extras
brew install diff-so-fancy
brew install gh

# Remove outdated versions from the cellar
brew cleanup
