syntax enable                     " Turn on syntax highlighting.

let mapleader = ","               " map <leader> key to ,
let g:mapleader = ","             " and again

nmap <leader>w :w!<cr>            " Fast saving

set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.

set cmdheight=2                   "The commandbar height

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set number                        " Show line numbers.
set ruler                         " Show cursor position.
set cursorline                    " Higlight current line
set cursorcolumn                  " Highlight current column
set list listchars=tab:»·,trail:· " Display extra whitespace

set visualbell                    " No beeping.

set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs

nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>